In [16]:
import requests
import os
import pandas as pd
from bs4 import BeautifulSoup
import time
import random

# Create a directory to store the downloaded HTML files
if not os.path.exists("team"):
    os.makedirs("team")

# Download the MVP voting results for each year from 1991 to 2021
years = list(range(1991, 2024))
url_start = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"
for year in years:
    filename = "team/{}.html".format(year)
    if os.path.exists(filename):
        print(f"{filename} already exists, skipping download")
    else:
        url = url_start.format(year)
        response = requests.get(url)
        with open(filename, "w+", encoding="utf-8") as f:
            f.write(response.text)
        print(f"{filename} downloaded")
    time.sleep(random.randint(6, 10))

team/1991.html already exists, skipping download
team/1992.html downloaded
team/1993.html downloaded
team/1994.html downloaded
team/1995.html downloaded
team/1996.html downloaded
team/1997.html downloaded
team/1998.html downloaded
team/1999.html downloaded
team/2000.html downloaded
team/2001.html downloaded
team/2002.html downloaded
team/2003.html downloaded
team/2004.html downloaded
team/2005.html downloaded
team/2006.html downloaded
team/2007.html downloaded
team/2008.html downloaded
team/2009.html downloaded
team/2010.html downloaded
team/2011.html downloaded
team/2012.html downloaded
team/2013.html downloaded
team/2014.html downloaded
team/2015.html downloaded
team/2016.html downloaded
team/2017.html downloaded
team/2018.html downloaded
team/2019.html downloaded
team/2020.html downloaded
team/2021.html downloaded
team/2022.html downloaded
team/2023.html downloaded

In [18]:
dfs = []

for year in years:
    with open("team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [19]:
teams = pd.concat(dfs)

In [20]:
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0  56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics*
1  44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers*
2  39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks*
3  30  52  .366  26.0  101.4  106.4  -4.84  1991   Washington Bullets
4  26  56  .317  30.0  102.9  107.5  -4.53  1991      New Jersey Nets

In [21]:
teams.to_csv("teams.csv")